import os

PAPER_TRADING = True
MAX_DAILY_LOSS = 5000.0
MAX_DRAWDOWN_PCT = 2.0
VIX_HIGH_THRESHOLD = 22.0

PRIMARY_BROKER = "ANGEL_ONE"
SECONDARY_BROKER = "ZERODHA"

TELEGRAM_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "YOUR_CHAT_ID")
